export const OPEN_NAV_MENU = 'OPEN_NAV_MENU';
export const CLOSE_NAV_MENU = 'CLOSE_NAV_MENU';

export const OPEN_LISTING_MENU = 'OPEN_LISTING_MENU';
export const CLOSE_LISTING_MENU = 'CLOSE_LISTING_MENU';

export const CHANGE_NAV_MENU_ACTIVE_TAB = 'CHANGE_NAV_MENU_ACTIVE_TAB';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
// export const RECEIVE_BUNDLES = 'RECEIVE_BUNDLES';

export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE';

export const RECEIVE_AUTH_DATA = 'RECEIVE_AUTH_DATA';

export const RECEIVE_SELF_ID = 'RECEIVE_SELF_ID';
export const RECEIVE_ENTITY = 'RECEIVE_ENTITY';


export const PAGE_VISITED = 'PAGE_VISITED';
export const SET_PAGE_HEIGHT = 'SET_PAGE_HEIGHT';


export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE';

